version: '3.8'

services:
  # Сервис Ollama для запуска языковой модели
  ollama:
    image: ollama/ollama:latest
    container_name: smartnlu-ollama
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ./.ollama:/root/.ollama
    healthcheck:
      # Проверяем, что Ollama API в целом доступен
      test: ["CMD-SHELL", "curl -sf http://localhost:11434/api/tags > /dev/null 2>&1"]
      interval: 15s
      timeout: 10s
      retries: 10
      start_period: 30s # Даем время на старт

  # Сервис Go для обработки запросов классификации
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: smartnlu-api
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - OLLAMA_HOST=http://ollama:11434
    depends_on:
      - ollama
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:8080/health || exit 1"]
      interval: 10s
      retries: 5
    command: ./server 

  # Сервис распознавания речи Vosk
  stt:
    image: alphacep/kaldi-vosk-server:latest
    container_name: smartnlu-stt
    restart: unless-stopped
    ports:
      - "2700:2700"
    environment:
      - VOSK_SAMPLE_RATE=16000
      - VOSK_MODEL_PATH=/models/ru
    volumes:
      - ./models/vosk-ru:/models/ru
    command: /opt/vosk-server/websocket/asr_server.py